FROM intel/oneapi-basekit:latest

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://ollama.com/install.sh | sh

RUN apt-get update && apt-get install -y \
    clinfo \
    intel-opencl-icd \
    ocl-icd-opencl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN clinfo | grep -i intel

# ENV OLLAMA_LLM_LIBRARY=opencl
# ENV ONEAPI_DEVICE_SELECTOR=opencl:gpu

# ENV ONEAPI_DEVICE_SELECTOR=level_zero:gpu

ENTRYPOINT ["ollama"]
CMD ["serve"]