services:
  ollama-ai:
    build:
      context: .
      dockerfile: Dockerfile.ollama-intel
      args:
        IPEXLLM_RELEASE_REPO: intel/ipex-llm
        IPEXLLM_RELEASE_VERSON: v2.2.0-nightly
        IPEXLLM_PORTABLE_ZIP_FILENAME: ollama-ipex-llm-2.2.0b20250313-ubuntu.tgz
    container_name: ollama-ai
    devices:
      - /dev/dri:/dev/dri
    ########
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
    environment:
      - ONEAPI_DEVICE_SELECTOR=level_zero:0
      - IPEX_LLM_NUM_CTX=16384
    restart: unless-stopped
    networks:
      - shared-network

  chroma-ai:
    image: chromadb/chroma
    container_name: chroma-ai
    volumes:
      - ./chroma:/chroma/chroma
    expose:
      - 8000
    restart: unless-stopped
    networks:
      - shared-network

  cache-ai:
    image: redis
    container_name: cache-ai
    expose:
      - ${REDIS_PORT}
    volumes:
      - ai-rds-data:/data
      - ai.redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  ai-rds-data:
  ai.redis.conf:


networks:
  shared-network:
    external: true
