services:
  ollama-ai:
    image: ollama/ollama
    container_name: ollama-ai
    devices:
      - "/dev/dri/card1:/dev/dri/card1"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    # devices:
    #   - /dev/dri
    environment:
      - LIBGL_ALWAYS_SOFTWARE=0
    ########
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    networks:
      - shared-network

  chroma-ai:
    image: chromadb/chroma
    container_name: chroma-ai
    expose:
      - 8000
    ports:
      - 8010:8000
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
